CREATE DATABASE IF NOT EXISTS ConsultasMedicas;

USE ConsultasMedicas;

CREATE TABLE IF NOT EXISTS MEDICO (
    MEDCODIGO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MEDNOME VARCHAR(50) NOT NULL,
    CRM VARCHAR(10) NOT NULL,
    ESPECIALIDADE VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PACIENTE (
    PACCODIGO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PACONOME VARCHAR(50) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS CONSULTA (
    CONCODIGO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MEDCODIGO INT,
    PACCODIGO INT,
    DATACONSULTA DATE NOT NULL,
    HORARIO TIME NOT NULL,
    DIAGNOSTICO TEXT,
    FOREIGN KEY (MEDCODIGO) REFERENCES MEDICO(MEDCODIGO),
    FOREIGN KEY (PACCODIGO) REFERENCES PACIENTE(PACCODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PRESCRICAO (
    CONCODIGO INT UNSIGNED,
    MDCODIGO INT UNSIGNED,
    PRIMARY KEY(CONCODIGO, MDCODIGO),
    FOREIGN KEY (CONCODIGO) REFERENCES CONSULTA(CONCODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS MEDICAMENTO (
    MDCODIGO INT AUTO_INCREMENT PRIMARY KEY,
    MDNOME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
